import type { Career, Encounters, Performance, Recap } from "./api.js";

// Canned bridge responses for the stories. These exist so the career, session,
// last-match and encounters screens can be drawn and diffed without a live
// client. Nothing in the running app imports this file.

export const CAREER: Career = {
  name: "SilentEnt#GG",
  rank: "Diamond 3",
  peakRank: "Ascendant 3",
  agents: [
    { agent: "KAY/O", games: 42, winRate: 61, kd: 1.34 },
    { agent: "Viper", games: 28, winRate: 54, kd: 1.12 },
    { agent: "Chamber", games: 19, winRate: 47, kd: 1.28 },
    { agent: "Sova", games: 11, winRate: 36, kd: 0.91 },
  ],
  maps: [
    { map: "Icebox", games: 24, winRate: 67, kd: 1.41 },
    { map: "Ascent", games: 21, winRate: 52, kd: 1.19 },
    { map: "Lotus", games: 18, winRate: 44, kd: 1.02 },
    { map: "Split", games: 12, winRate: 33, kd: 0.88 },
  ],
  matches: [
    {
      map: "Icebox",
      agent: "KAY/O",
      result: "Victory",
      score: "13-9",
      kills: 24,
      deaths: 14,
      assists: 6,
      kd: 1.71,
      acs: 291,
      delta: 22,
    },
    {
      map: "Ascent",
      agent: "KAY/O",
      result: "Defeat",
      score: "8-13",
      kills: 15,
      deaths: 19,
      assists: 4,
      kd: 0.79,
      acs: 198,
      delta: -17,
    },
    {
      map: "Lotus",
      agent: "Viper",
      result: "Victory",
      score: "13-11",
      kills: 21,
      deaths: 17,
      assists: 9,
      kd: 1.24,
      acs: 246,
      delta: 19,
    },
    {
      map: "Split",
      agent: "Chamber",
      result: "Defeat",
      score: "6-13",
      kills: 11,
      deaths: 20,
      assists: 2,
      kd: 0.55,
      acs: 154,
      delta: -21,
    },
    {
      map: "Icebox",
      agent: "KAY/O",
      result: "Victory",
      score: "13-4",
      kills: 27,
      deaths: 9,
      assists: 7,
      kd: 3.0,
      acs: 348,
      delta: 26,
    },
  ],
  encounter: { seen: 7, withYou: 3, againstYou: 4, wins: 4, losses: 3 },
};

export const PERFORMANCE: Performance = {
  summary: {
    matches: 38,
    wins: 21,
    losses: 17,
    winRate: 55,
    net: 84,
    avgWin: 21,
    avgLoss: -16,
    current: { tier: 20, name: "Diamond 3", group: "Diamond", color: "#D864C7", rr: 72 },
    exactResults: 38,
  },
  points: [
    { delta: 22, rr: 22, result: "Victory", map: "Icebox" },
    { delta: -17, rr: 5, result: "Defeat", map: "Ascent" },
    { delta: 19, rr: 24, result: "Victory", map: "Lotus" },
    { delta: -21, rr: 3, result: "Defeat", map: "Split" },
    { delta: 26, rr: 29, result: "Victory", map: "Icebox" },
    { delta: 18, rr: 47, result: "Victory", map: "Haven" },
    { delta: -14, rr: 33, result: "Defeat", map: "Pearl" },
    { delta: 24, rr: 57, result: "Victory", map: "Icebox" },
    { delta: -9, rr: 48, result: "Defeat", map: "Bind" },
    { delta: 24, rr: 72, result: "Victory", map: "Ascent" },
  ],
  splits: {
    maps: [
      { map: "Icebox", games: 12, winRate: 75, kd: 1.44 },
      { map: "Ascent", games: 9, winRate: 56, kd: 1.18 },
      { map: "Haven", games: 7, winRate: 43, kd: 1.02 },
      { map: "Split", games: 5, winRate: 20, kd: 0.86 },
    ],
    agents: [
      { agent: "KAY/O", games: 18, winRate: 61, kd: 1.34 },
      { agent: "Viper", games: 11, winRate: 55, kd: 1.11 },
      { agent: "Chamber", games: 6, winRate: 33, kd: 1.21 },
    ],
  },
  insights: [
    { title: "You win 75% on Icebox", detail: "12 games, well above your 55% overall" },
    { title: "Split is costing you RR", detail: "1 win in 5, net −58" },
    { title: "Your K/D holds up in losses", detail: "1.02 in defeats vs 1.31 in wins" },
  ],
};

export const RECAP: Recap = {
  matchId: "demo",
  map: "Icebox",
  mode: "Competitive",
  result: "Victory",
  scores: { Blue: 13, Red: 9 },
  rrDelta: 22,
  you: {
    puuid: "self",
    name: "Day#9932",
    adr: 148,
    kast: 74,
    firstBloods: 1,
    topWeapon: { name: "Phantom", kills: 14 },
    team: "Blue",
    agent: "Chamber",
    kills: 19,
    deaths: 14,
    assists: 5,
    kd: 1.36,
    acs: 264,
    hsPct: 31,
  },
  mvp: { name: "SilentEnt#GG", agent: "KAY/O", acs: 348, kd: 3.0 },
  players: [
    {
      puuid: "SilentEnt#GG",
      name: "SilentEnt#GG",
      adr: 172,
      kast: 82,
      firstBloods: 3,
      firstDeaths: 1,
      econ: 78,
      clutches: 2,
      clutchesLost: 1,
      plants: 3,
      plantsWon: 2,
      defuses: 0,
      defusesWon: 0,
      multiKills: { "2": 3, "3": 1 },
      topWeapon: { name: "Vandal", kills: 18 },
      weaponKills: [
        { name: "Vandal", kills: 18 },
        { name: "Sheriff", kills: 5 },
        { name: "Classic", kills: 3 },
        { name: "Operator", kills: 1 },
      ],
      team: "Blue",
      agent: "KAY/O",
      rank: "Diamond 3",
      rankColor: "#D864C7",
      kills: 27,
      deaths: 9,
      assists: 7,
      kd: 3.0,
      acs: 348,
      hsPct: 28,
    },
    {
      puuid: "Day#9932",
      name: "Day#9932",
      adr: 148,
      kast: 74,
      firstBloods: 1,
      firstDeaths: 2,
      econ: 61,
      clutches: 1,
      clutchesLost: 2,
      plants: 1,
      plantsWon: 1,
      defuses: 1,
      defusesWon: 1,
      multiKills: { "2": 2 },
      topWeapon: { name: "Phantom", kills: 14 },
      team: "Blue",
      agent: "Chamber",
      rank: "Gold 2",
      kills: 19,
      deaths: 14,
      assists: 5,
      kd: 1.36,
      acs: 264,
      hsPct: 31,
    },
    {
      puuid: "PixelAndy#KR",
      name: "PixelAndy#KR",
      adr: 96,
      kast: 61,
      firstBloods: 0,
      topWeapon: { name: "Spectre", kills: 9 },
      team: "Blue",
      agent: "Astra",
      rank: "Silver 3",
      kills: 12,
      deaths: 15,
      assists: 14,
      kd: 0.8,
      acs: 178,
      hsPct: 19,
    },
    {
      puuid: "DriftFrag#RR",
      name: "DriftFrag#RR",
      adr: 131,
      kast: 68,
      firstBloods: 2,
      topWeapon: { name: "Vandal", kills: 12 },
      team: "Blue",
      agent: "Reyna",
      rank: "Bronze 3",
      kills: 16,
      deaths: 16,
      assists: 2,
      kd: 1.0,
      acs: 221,
      hsPct: 24,
    },
    {
      puuid: "VexedSmoke#1337",
      name: "VexedSmoke#1337",
      adr: 78,
      kast: 52,
      firstBloods: 0,
      topWeapon: { name: "Classic", kills: 6 },
      team: "Blue",
      agent: "Raze",
      rank: "Unranked",
      kills: 9,
      deaths: 17,
      assists: 6,
      kd: 0.53,
      acs: 141,
      hsPct: 13,
    },
    {
      puuid: "NeonLock#VAL",
      name: "NeonLock#VAL",
      adr: 158,
      kast: 76,
      firstBloods: 2,
      topWeapon: { name: "Vandal", kills: 17 },
      team: "Red",
      agent: "Clove",
      rank: "Diamond 3",
      rankColor: "#D864C7",
      kills: 22,
      deaths: 17,
      assists: 4,
      kd: 1.29,
      acs: 279,
      hsPct: 25,
    },
    {
      puuid: "GhostMain#GG",
      name: "GhostMain#GG",
      adr: 124,
      kast: 70,
      firstBloods: 1,
      topWeapon: { name: "Phantom", kills: 13 },
      team: "Red",
      agent: "Fade",
      rank: "Gold 3",
      kills: 18,
      deaths: 18,
      assists: 8,
      kd: 1.0,
      acs: 232,
      hsPct: 19,
    },
    {
      puuid: "FrostSpike#VAL",
      name: "FrostSpike#VAL",
      adr: 103,
      kast: 58,
      firstBloods: 1,
      topWeapon: { name: "Vandal", kills: 10 },
      team: "Red",
      agent: "Yoru",
      rank: "Silver 3",
      kills: 14,
      deaths: 19,
      assists: 3,
      kd: 0.74,
      acs: 196,
      hsPct: 30,
    },
    {
      puuid: "DriftAim#GG",
      name: "DriftAim#GG",
      adr: 99,
      kast: 64,
      firstBloods: 0,
      topWeapon: { name: "Sheriff", kills: 8 },
      team: "Red",
      agent: "Skye",
      rank: "Bronze 3",
      kills: 13,
      deaths: 18,
      assists: 11,
      kd: 0.72,
      acs: 184,
      hsPct: 27,
    },
    {
      puuid: "GhostDash#OCE",
      name: "GhostDash#OCE",
      adr: 81,
      kast: 49,
      firstBloods: 0,
      topWeapon: { name: "Classic", kills: 7 },
      team: "Red",
      agent: "Phoenix",
      rank: "Bronze 2",
      kills: 11,
      deaths: 20,
      assists: 5,
      kd: 0.55,
      acs: 163,
      hsPct: 14,
    },
  ],
};

export const ENCOUNTERS: Encounters = {
  accountCount: 214,
  scope: "current",
  players: [
    {
      // The shape the backend actually sends: the six counters it keeps, and
      // the totals derived from them. The fixture used to carry the totals
      // alone, so this view drew correct numbers here and 0x 0W 0L against a
      // real backend, which sent the counters under different names entirely.
      puuid: "a",
      name: "NeonLock#VAL",
      rank: "Diamond 3",
      rankColor: "#D864C7",
      withCount: 5,
      againstCount: 4,
      winsWith: 3,
      lossesWith: 2,
      drawsWith: 0,
      winsAgainst: 3,
      lossesAgainst: 0,
      drawsAgainst: 1,
      seen: 9,
      wins: 6,
      losses: 2,
      draws: 1,
      lastMap: "Icebox",
    },
    {
      puuid: "b",
      name: "GhostMain#GG",
      rank: "Gold 3",
      seen: 6,
      wins: 2,
      losses: 4,
      lastMap: "Ascent",
    },
    {
      puuid: "c",
      name: "PixelAndy#KR",
      rank: "Silver 3",
      seen: 5,
      wins: 4,
      losses: 1,
      lastMap: "Lotus",
    },
    {
      puuid: "d",
      name: "FrostSpike#VAL",
      rank: "Silver 3",
      seen: 4,
      wins: 1,
      losses: 3,
      lastMap: "Split",
    },
    {
      puuid: "e",
      name: "DriftAim#GG",
      rank: "Bronze 3",
      seen: 3,
      wins: 2,
      losses: 1,
      lastMap: "Haven",
    },
    {
      puuid: "f",
      name: "Quickbtw#KR",
      rank: "Ascendant 1",
      seen: 2,
      wins: 1,
      losses: 1,
      lastMap: "Pearl",
    },
    {
      puuid: "x0",
      name: "LurkSmoke#NA1",
      rank: "Gold 1",
      seen: 2,
      wins: 1,
      losses: 1,
      lastMap: "Ascent",
    },
    {
      puuid: "x1",
      name: "HazyFlick#APAC",
      rank: "Silver 2",
      seen: 4,
      wins: 2,
      losses: 2,
      lastMap: "Bind",
    },
    {
      puuid: "x2",
      name: "CrimsonDash#AP",
      rank: "Platinum 1",
      seen: 6,
      wins: 3,
      losses: 3,
      lastMap: "Haven",
    },
    {
      puuid: "x3",
      name: "SageDiff#EUW",
      rank: "Bronze 2",
      seen: 5,
      wins: 4,
      losses: 1,
      lastMap: "Split",
    },
    {
      puuid: "x4",
      name: "DriftAce#KR",
      rank: "Diamond 1",
      seen: 3,
      wins: 1,
      losses: 2,
      lastMap: "Lotus",
    },
    {
      puuid: "x5",
      name: "PixelEnt#000",
      rank: "Gold 3",
      seen: 5,
      wins: 2,
      losses: 3,
      lastMap: "Sunset",
    },
    {
      puuid: "x6",
      name: "QuickSpike#VAL",
      rank: "Silver 1",
      seen: 4,
      wins: 3,
      losses: 1,
      lastMap: "Breeze",
    },
    {
      puuid: "x7",
      name: "Riotyt#000",
      rank: "Platinum 3",
      seen: 6,
      wins: 4,
      losses: 2,
      lastMap: "Fracture",
    },
    {
      puuid: "x8",
      name: "SilentAce#NA1",
      rank: "Bronze 1",
      seen: 4,
      wins: 1,
      losses: 3,
      lastMap: "Pearl",
    },
    {
      puuid: "x9",
      name: "NeonDash#BR",
      rank: "Gold 2",
      seen: 3,
      wins: 2,
      losses: 1,
      lastMap: "Icebox",
    },
    {
      puuid: "x10",
      name: "FrostAim#LAT",
      rank: "Silver 3",
      seen: 5,
      wins: 3,
      losses: 2,
      lastMap: "Abyss",
    },
    {
      puuid: "x11",
      name: "GhostLock#KR",
      rank: "Platinum 2",
      seen: 7,
      wins: 4,
      losses: 3,
      lastMap: "Corrode",
    },
    {
      puuid: "x12",
      name: "EchoFrag#EU",
      rank: "Bronze 3",
      seen: 2,
      wins: 1,
      losses: 1,
      lastMap: "Ascent",
    },
    {
      puuid: "x13",
      name: "LurkAce#OCE",
      rank: "Ascendant 2",
      seen: 4,
      wins: 2,
      losses: 2,
      lastMap: "Haven",
    },
  ],
};
