import type { Board, Player } from "./types.js";

// A fixed board for the preview and the render self-check. It is never served
// to anyone: the app shows the holding screen when there is no live client,
// and nothing in the running app imports this outside those two paths.

function player(over: Partial<Player>): Player {
  return {
    puuid: over.name ?? "x",
    nameHidden: false,
    isSelf: false,
    levelHidden: false,
    smurf: false,
    form: ["W", "L", "W", "W", "L"],
    ...over,
  };
}

const BLUE: Player[] = [
  player({
    name: "SilentEnt#GG",
    team: "Blue",
    agent: "KAY/O",
    role: "Initiator",
    rankTier: 20,
    rank: "Diamond 3",
    rankColor: "#D864C7",
    rr: 72,
    rrEarned: 18,
    peakRankTier: 23,
    peakRank: "Ascendant 3",
    peakColor: "#189452",
    peakAct: "V25 Act 3",
    previousRank: "Diamond 2",
    winRate: 64,
    games: 349,
    kd: 1.9,
    hsPct: 24,
    level: 50,
    smurf: true,
    smurfReasons: ["Lvl 50, peak Ascendant 3", "K/D 1.9 at lvl 50", "64% WR"],
    streak: { type: "W", count: 4 },
    topAgents: [
      { agent: "KAY/O", games: 6 },
      { agent: "Viper", games: 2 },
    ],
    mapWinRate: { winRate: 67, games: 6 },
    weapons: [{ weapon: "Vandal", skin: { name: "Reaver" } }],
    title: "Legend",
    party: { id: "a", color: "#E34343", number: 1, size: 3 },
  }),
  player({
    name: "Day#9932",
    team: "Blue",
    agent: "Chamber",
    role: "Sentinel",
    rankTier: 13,
    rank: "Gold 2",
    rankColor: "#C5BA3F",
    rr: 37,
    rrEarned: -12,
    peakRankTier: 14,
    peakRank: "Gold 3",
    peakAct: "V25 Act 4",
    previousRank: "Gold 1",
    winRate: 52,
    games: 118,
    kd: 0.91,
    hsPct: 33,
    level: 154,
    isSelf: true,
    party: { id: "a", color: "#E34343", number: 1, size: 3 },
  }),
  player({
    name: "PixelAndy#KR",
    encounter: { withCount: 4, againstCount: 0, winsWith: 3, lossesWith: 1 },
    team: "Blue",
    agent: "Astra",
    role: "Controller",
    rankTier: 11,
    rank: "Silver 3",
    rr: 35,
    peakRank: "Silver 3",
    previousRank: "Silver 2",
    winRate: 49,
    games: 154,
    kd: 1.05,
    hsPct: 19,
    level: 300,
    party: { id: "a", color: "#E34343", number: 1, size: 3 },
  }),
  player({
    name: "DriftFrag#RR",
    team: "Blue",
    agent: "Reyna",
    role: "Duelist",
    rankTier: 8,
    rank: "Bronze 3",
    rr: 96,
    rrEarned: 21,
    peakRank: "Silver 1",
    previousRank: "Bronze 1",
    winRate: 53,
    games: 21,
    kd: 1.42,
    hsPct: 24,
    level: 227,
  }),
  player({
    name: "VexedSmoke#1337",
    team: "Blue",
    agent: "Raze",
    role: "Duelist",
    rankTier: 0,
    rank: "Unranked",
    peakRank: "Gold 1",
    previousRank: "Bronze 1",
    winRate: 0,
    games: 0,
    kd: null,
    level: 12,
    levelHidden: true,
  }),
];

const RED: Player[] = [
  player({
    name: "NeonLock#VAL",
    encounter: {
      withCount: 2,
      againstCount: 7,
      winsWith: 1,
      lossesWith: 1,
      winsAgainst: 3,
      lossesAgainst: 4,
    },
    team: "Red",
    agent: "Clove",
    role: "Controller",
    rankTier: 20,
    rank: "Diamond 3",
    rankColor: "#D864C7",
    rr: 97,
    rrEarned: -12,
    peakRankTier: 22,
    peakRank: "Ascendant 2",
    peakAct: "V25 Act 5",
    previousRank: "Platinum 3",
    winRate: 64,
    games: 227,
    kd: 1.79,
    hsPct: 25,
    level: 43,
    smurf: true,
    smurfReasons: ["Lvl 43, peak Ascendant 2"],
    streak: { type: "W", count: 5 },
    party: { id: "b", color: "#D843E3", number: 2, size: 2 },
  }),
  player({
    name: "GhostMain#GG",
    team: "Red",
    agent: "Fade",
    role: "Initiator",
    rankTier: 14,
    rank: "Gold 3",
    rr: 11,
    rrEarned: 17,
    peakRank: "Platinum 3",
    previousRank: "Gold 1",
    winRate: 51,
    games: 216,
    kd: 1.5,
    hsPct: 19,
    level: 127,
    party: { id: "b", color: "#D843E3", number: 2, size: 2 },
  }),
  player({
    name: "FrostSpike#VAL",
    stackGuess: {
      id: "guess-0",
      size: 2,
      confidence: 98,
      members: ["frost", "driftaim"],
      shared: 5,
      same: 5,
    },
    team: "Red",
    agent: "Yoru",
    role: "Duelist",
    rankTier: 11,
    rank: "Silver 3",
    rr: 16,
    peakRank: "Gold 3",
    previousRank: "Silver 2",
    winRate: 63,
    games: 147,
    kd: 0.73,
    hsPct: 30,
    level: 99,
    nameHidden: true,
  }),
  player({
    name: "DriftAim#GG",
    stackGuess: {
      id: "guess-0",
      size: 2,
      confidence: 98,
      members: ["frost", "driftaim"],
      shared: 5,
      same: 5,
    },
    team: "Red",
    agent: "Skye",
    role: "Initiator",
    rankTier: 8,
    rank: "Bronze 3",
    rr: 2,
    peakRank: "Gold 1",
    previousRank: "Bronze 2",
    winRate: 52,
    games: 174,
    kd: 0.93,
    hsPct: 27,
    level: 181,
    streak: { type: "L", count: 3 },
  }),
  player({
    name: "GhostDash#OCE",
    team: "Red",
    agent: "Phoenix",
    role: "Duelist",
    rankTier: 7,
    rank: "Bronze 2",
    rr: 70,
    peakRank: "Silver 2",
    previousRank: "Bronze 2",
    winRate: 42,
    games: 345,
    kd: 0.9,
    hsPct: 14,
    level: 156,
  }),
];

export const SAMPLE_BOARD: Board = {
  state: "INGAME",
  stateLabel: "In Game",
  source: "demo",
  map: "Icebox",
  mode: "Competitive",
  side: "Defense",
  selfTeam: "Blue",
  players: [...BLUE, ...RED],
  teams: { Blue: BLUE, Red: RED },
  teamStats: {
    Blue: { avgRank: "Gold 1", avgKd: 1.5, avgWinRate: 56, smurfCount: 1, size: 5 },
    Red: { avgRank: "Gold 1", avgKd: 1.17, avgWinRate: 54, smurfCount: 1, size: 5 },
  },
  parties: [
    { id: "a", color: "#E34343", number: 1, size: 3 },
    { id: "b", color: "#D843E3", number: 2, size: 2 },
  ],
  score: { ally: 3, enemy: 1, round: 5 },
  winProb: 56,
  session: {
    net: -1,
    points: [
      { map: "Summit", result: "Defeat", delta: -20, rr: 33 },
      { map: "Fracture", result: "Defeat", delta: -15, rr: 18 },
      { map: "Haven", result: "Defeat", delta: -27, rr: 91 },
      { map: "Ascent", result: "Victory", delta: 22, rr: 13 },
      { map: "Pearl", result: "Victory", delta: 12, rr: 25 },
      { map: "Icebox", result: "Victory", delta: 27, rr: 52 },
    ],
  },
  appVersion: "2.1.0",
};
